name: Lambda Deployment

on:
  push:
    branches: [ main ]
    paths:
      - 'lambda/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2  # To be able to get changed files
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22'
    
    - name: Install dependencies
      run: npm install

    # install CDK
    - name: Install CDK
      run: |
        npm install -g aws-cdk
    
    - name: Run unit tests
      run: npm run test:unit

    - name: CDK deploy if unit tests pass
      run: |
        if [ $? -eq 0 ]; then
          cdk deploy LambdaCanaryStack-Dev --require-approval never
        else
          echo "Unit tests failed. Skipping CDK deployment."
        fi
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-west-2
     
    # run integration tests
    - name: Integration tests
      run: |
        npm run test:integration
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-west-2

    # deploy to production
    - name: Deploy to production
      run: |
        cdk deploy LambdaCanaryStack-Prod --require-approval never
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-west-2
